---
openapi: 3.0.3
info:
  title: onecx-help helps import from file during the start of the application
  version: 1.0.0
servers:
  - url: "http://localhost"
paths:
  /import/help:
    post:
      security:
        - oauth2: [ ocx-hp:write ]
      operationId: importHelp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataImport'
      responses:
        200:
          description: ok
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-hp:write: Grants write access
  schemas:
    DataImport:
      type: object
      properties:
        helps:
          $ref: '#/components/schemas/DataImportTenantHelps'
    DataImportTenantHelps:
      type: object
      nullable: false
      additionalProperties:
        $ref: '#/components/schemas/DataImportHelps'
    DataImportHelps:
      type: object
      nullable: false
      additionalProperties:
        $ref: '#/components/schemas/DataImportHelp'
    DataImportHelp:
      type: object
      properties:
        context:
          type: string
        baseUrl:
          type: string
        resourceUrl:
          type: string
        productName:
          type: string
